### ISSUE TITLE
Volume slider gets cut in youtube music app

### ISSUE THREAD

**Issue by jramosss** [volkanakinpasa/youtubetospotify#23]
Hi! Really great extension, saves me a few clicks.
I am using it both in chrome and in youtube music app (linux, ubuntu 22.04.1 LTS)
In chrome i don't have any trouble, but in youtube music, there is this error where the volume slider gets "shortened" because of the spotify icon interrupting its way.
I noticed that it fixes itself when i change monitors (from my laptop monitor to an external monitor)
It also fixes itself when changing song, so it appears to happen only in the first time i start the app.

Expected:
![Expected](https://i.imgur.com/NhRPBU6.gif)
Error:
![Error](https://i.imgur.com/qIcksWu.gif)

**Comment by volkanakinpasa** [comment]
Hi,
That’s a very good feedback. I will take a look at it asap and let you know once it’s fixed 👍 

Thank you @jramosss

**Comment by volkanakinpasa** [comment]
@jramosss 
Meanwhile could you supply 
- a video screen shot?
- Chrome version?

**Comment by jramosss** [comment]
My chrome version: 110.0.5481.100 (Official Build) (64-bit) 

About the video, what do you want to see specifically?
What do you want to observe other than the behavior i have shown in the gif?

**Comment by volkanakinpasa** [comment]
Ohh my bad. You already mentioned the issue is happening in YT Music. I'm working on it ...

**Comment by volkanakinpasa** [comment]
Fixed and deployed with new version, hope to be approved in couple of hours. Make sure the extension has the lates version "9.2.3"

https://github.com/volkanakinpasa/youtubetospotify/releases/tag/9.2.3
